# Generated by Django 4.1.1 on 2022-09-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, verbose_name='Kitopni nomi')),
                ('sahifa', models.PositiveIntegerField(max_length=300, verbose_name='Sahifa')),
                ('yil', models.DateField(verbose_name='yili')),
                ('janr', models.CharField(max_length=50, verbose_name='janr')),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=40, verbose_name='ismi')),
                ('ragam', models.PositiveIntegerField(max_length=30, verbose_name='st_ragam')),
                ('kurs', models.PositiveIntegerField(max_length=5, verbose_name='kursi')),
                ('soni_kt', models.PositiveIntegerField(max_length=100, verbose_name='kitoblar_soni')),
            ],
        ),
        migrations.CreateModel(
            name='Yozuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25, verbose_name='ismi')),
                ('tirik', models.BooleanField()),
                ('tugilgan_yil', models.PositiveIntegerField(max_length=10, verbose_name='tugilgan_yil')),
                ('millat', models.CharField(max_length=30, verbose_name='millati')),
            ],
        ),
    ]
