# Generated by Django 4.1.1 on 2022-09-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='janr',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kitob',
            name='nom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='kitob',
            name='sahifa',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kitob',
            name='yil',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='ism',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='kurs',
            field=models.PositiveIntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='ragam',
            field=models.PositiveIntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='soni_kt',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='yozuvchi',
            name='tugilgan_yil',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
