# Generated by Django 4.1.1 on 2022-09-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_kitob_janr_alter_kitob_nom_alter_kitob_sahifa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='sahifa',
            field=models.PositiveIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='soni_kt',
            field=models.PositiveIntegerField(max_length=15),
        ),
    ]
