# Generated by Django 4.1.1 on 2022-09-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_kitob_sahifa_alter_talaba_soni_kt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='sahifa',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='kurs',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='ragam',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='soni_kt',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='yozuvchi',
            name='tugilgan_yil',
            field=models.PositiveIntegerField(),
        ),
    ]
