# Generated by Django 4.1.2 on 2022-10-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_kitob_sahifa_alter_talaba_kurs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talaba',
            old_name='ragam',
            new_name='yosh',
        ),
    ]
