# Generated by Django 4.1.1 on 2022-10-06 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_talaba_soni_kt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('qaytardi', models.CharField(choices=[['Ha', 'Ha'], ['Yog', 'Yog']], max_length=50)),
                ('qaytarilgan_sana', models.DateField()),
                ('kitob', models.ForeignKey(choices=[['Ha', 'Ha'], ['Yog', 'Yog']], default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.kitob')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.talaba')),
            ],
        ),
    ]
